### PR TITLE
Mockup for the topbar

### PR DESCRIPTION
**Pull request by Hepic**

### CODE REVIEW

**Comment by Hepic** [comment]
pic2
pic1

**Comment by gtklocker** [comment]
The avatar should have the same margin to the right as Ting on the left.

**Comment by dionyziz** [comment]
Use gray background for the user menu.

**Comment by dionyziz** [comment]
Pointer arrow should point to the horizonal middle of the avatar.

**Comment by dionyziz** [comment]
Consider using rounded corners in the user menu.

**Comment by Hepic** [comment]
pic

**Comment by dionyziz** [comment]
Make the top-rigth corner for the user menu rounded.

**Comment by dionyziz** [comment]
Provide screenshot of how the hover effect appears in the user menu.

**Comment by Hepic** [comment]
pic

**Comment by Hepic** [comment]
pic

**Comment by Hepic** [comment]
pic

**Comment by dionyziz** [comment]
Avoid checking in .DS_Store files. Put it in .gitignore.

**Comment by Hepic** [comment]
I don't undestand it.

**Pull request merged**
