### PR TITLE
Make heights of messages auto

### PR DESCRIPTION
**Pull request by Hepic**

### CODE REVIEW

**Comment by dionyziz** [comment]
Screenshot

**Comment by Hepic** [comment]
screenshot from 2015-11-07 11 46 40

**Comment by dionyziz** [comment]
The bubble arrow is pointing the wrong way in your screenshots. It should be pointing to the username. So, up when wrapped if you're going to wrap this way. Please also include a screenshot of how your changes affect non-wrapped messages

**Comment by Hepic** [comment]
screenshot from 2015-11-07 18 38 12

**Comment by Hepic** [comment]
Still it has some issues if the username is bigger. So I need to fix that.

**Comment by dionyziz** [comment]
Looks good so far. Please use the WIP flag to mark the PR as pending.

**Comment by Hepic** [comment]
screenshot from 2015-11-08 00 15 56

**Comment by Hepic** [comment]
That works, but it is the first way we discussed.
Should leave it as it is, or convert it to the second way?

**Comment by dionyziz** [comment]
It troubles me that the "test" text within the gray box has extraneous padding on the right.

**Comment by Hepic** [comment]
screenshot from 2015-11-16 20 48 09

**Comment by dionyziz** [comment]
Squash

**Comment by dionyziz** [comment]
Please fix your commit message. Your commit message should contain a short description in the first line, and a longer description (optionally) in the rest of the lines, leaving the second line blank. Please look around the web for guides on how to write good commit messages.

**Comment by dionyziz** [comment]
In your screenshot, I see one avatar has collapsed. Can we get that fixed?

**Comment by Hepic** [comment]
I am not sure what happened, because I took a similar picture and there is not any problem . 
screenshot from 2015-11-21 09 17 41

**Pull request merged**
