### PR TITLE
Fix image display

### PR DESCRIPTION
**Pull request by Hepic**

### CODE REVIEW

**Comment by dionyziz** [comment]
Screenshot

**Comment by Hepic** [comment]
screenshot from 2017-09-19 18 01 57

**Comment by Hepic** [comment]
You approved before I send the screenshot. Does it look good ?

**Comment by dionyziz** [comment]
Still shows a scrollbar for certain images for me, see here:

screen shot 2017-09-19 at 18 43 16

Consider resizing with a flex property instead of max-width.

**Comment by Hepic** [comment]
pic

**Comment by gtklocker** [comment]
Would be nice if our images had rounded corners to match the bubble's rounded corners.

**Comment by Hepic** [comment]
pic

**Pull request merged**
